application: suite-house
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:


#Stylesheets directory, serve all files as static
- url: /stylesheets
  static_dir: stylesheets

#javascript directory
- url: /js
  static_dir: js

- url: /finance.*
  script: finance.finance.application

- url: /.*
  script: index.application

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest

